polygon:
  target: prod
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      role: "{{ env_var('ROLE') }}"
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}"
      region: "{{ env_var('REGION') }}"
      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      schema: "{{ env_var('SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
      query_tag: polygon_curator
    prod:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      role: "{{ env_var('ROLE') }}"
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}"
      region: "{{ env_var('REGION') }}"
      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      schema: "{{ env_var('SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
      query_tag: polygon_curator
    community_dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      # User/password auth
      user: "{{ env_var('SF_USERNAME') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE') }}"
      schema: "{{ env_var('SF_SCHEMA') }}"
      region: "{{ env_var('SF_REGION') }}"
      database: "{{ env_var('SF_DATABASE') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      threads: 4
      client_session_keep_alive: False
      query_tag: polygon_curator
