name: dbt_run_scheduled
run-name: dbt_run_scheduled

on:
  push:
    branches:
      - main
      - bug-fix-github-action
  schedule:
    # Runs "every 6 hours" (see https://crontab.guru)
    - cron: '0 */6 * * *'
    
env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: '["dbt run -m 1+models/silver/streamline/streamline__blocks_realtime.sql 1+models/silver/streamline/streamline__transactions_realtime.sql"]'
      environment: 'workflow_prod'
    secrets: inherit # pass all secrets
  


