version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: polygon_blocks
      - name: polygon_txs
  - name: crosschain
    database: flipside_prod_db
    schema: crosschain
    tables:
      - name: address_labels
  - name: symbols_cross_tab
    database: FLIPSIDE_PROD_DB
    schema: SILVER
    tables:
      - name: MARKET_ASSET_METADATA
  - name: polygon_dex_pools
    database: polygon
    schema: bronze
    tables:
      - name: SUSHI_DIM_DEX_POOLS
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices