version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: polygon_blocks
      - name: polygon_txs
  - name: crosschain
    database: flipside_prod_db
    schema: crosschain
    tables:
      - name: address_labels
  