version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: polygon_blocks
      - name: polygon_txs
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
  - name: symbols_cross_tab
    database: FLIPSIDE_PROD_DB
    schema: SILVER
    tables:
      - name: MARKET_ASSET_METADATA
  - name: polygon_dex_pools
    database: polygon
    schema: bronze
    tables:
      - name: SUSHI_DIM_DEX_POOLS
      - name: SUSHI_DIM_KASHI_PAIRS
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
      - name: DIM_CONTRACTS
      - name: DIM_DEX_LIQUIDITY_POOLS
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "POLYGON_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "POLYGON" }}
    tables:
      - name: blocks
      - name: transactions