version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'POLYGON' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: DIM_CONTRACTS
      - name: DIM_DEX_LIQUIDITY_POOLS
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ var('GLOBAL_PROD_DB_NAME') ~ ('_dev' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else '') }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceblockbynumber
      - name: decoded_logs
      - name: confirm_blocks
      - name: matic_balances
      - name: token_balances
      - name: blocks_v2
      - name: transactions_v2
      - name: receipts_v2
      - name: traces_v2
      - name: confirm_blocks_v2
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables:
      - name: node_mapping
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'POLYGON' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: apis_keys
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: polygon_silver
    database: polygon
    schema: silver
    tables:
      - name: verified_abis
      - name: overflowed_traces
      - name: overflowed_traces2
  - name: polygon_bronze_api
    database: polygon
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: polygon
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: external_polymarket
    database: external
    schema: polymarket
    tables:
      - name: dim_markets
  - name: polygon_gold
    database: "{{ 'polygon' if target.database == 'POLYGON' else 'polygon_dev' }}"
    schema: core
    tables:
      - name: fact_traces
